package chap15_exception;

public class _02_TryCatchFinally {
	public static void main(String[] args) {
		
	}
}
